### ISSUE TITLE
关于wireshark配置问题

### ISSUE THREAD

**Issue by 0x5f3759dg** [leolovenet/qqwry2mmdb#1]
**你好**：

   * 按照你给的配置图，配置wireshark的qqwry.mmdb的路径后
   * 没有显示出ip的city，和省信息,这个怎么配置

**Comment by leolovenet** [comment]
需要配置的路径为包含 qqwry.mmdb 的目录，不是直接指定这个文件的绝对路径哦

**Comment by mengyou658** [comment]
@theshaodi 
![](https://github.com/mengyou658/keywords/raw/master/all/imgs/wireshark-column-defined.png)
编辑列，类型选择customer，fields填写：ip.geoip.city就可以了
是需要自定义来展示

**Comment by 0x5f3759dg** [comment]
> @theshaodi
> ![](https://github.com/mengyou658/keywords/raw/master/all/imgs/wireshark-column-defined.png)
> 编辑列，类型选择customer，fields填写：ip.geoip.city就可以了
> 是需要自定义来展示

解决了我的问题

**Comment by 0x5f3759dg** [comment]
> 需要配置的路径为包含 qqwry.mmdb 的目录，不是直接指定这个文件的绝对路径哦

感谢分享
