### ISSUE TITLE
提示错误

### ISSUE THREAD

**Issue by bettworks** [leolovenet/qqwry2mmdb#2]
Can't locate IP/QQWry/Dumper.pm in @INC (you may need to install the IP::QQWry::Dumper module) (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at qqwry2mmdb.pl line 10.

关键是这个IP::QQWry::Dumper模块也安装不了。。。老大帮忙看看

**Comment by ghost** [comment]
最新数据 https://github.com/gai871013/ip-location/blob/master/src/QQWry.dat

**Comment by leolovenet** [comment]
IP::QQWry::Dumper 库文件在本项目中，一并下载使用即可

请看 [README](https://github.com/leolovenet/qqwry2mmdb#%E5%AE%89%E8%A3%85-qqwry2mmdbpl%E8%87%AA%E5%B7%B1%E7%94%9F%E6%88%90%E7%89%B9%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93%E6%96%87%E4%BB%B6) 更新了更加详细的使用步骤
已经在 CentOS7 上测试过，可以正常使用

**Comment by ghost** [comment]
> IP::QQWry::Dumper 库文件在本项目中，一并下载使用即可
> 
> 请看 [README](https://github.com/leolovenet/qqwry2mmdb#%E5%AE%89%E8%A3%85-qqwry2mmdbpl%E8%87%AA%E5%B7%B1%E7%94%9F%E6%88%90%E7%89%B9%E5%AE%9A%E6%95%B0%E6%8D%AE%E5%BA%93%E6%96%87%E4%BB%B6) 更新了更加详细的使用步骤 已经在 CentOS7 上测试过，可以正常使用

感谢解答，已经正常运行，比心~
