### ISSUE TITLE
想保留所有数据结构

### ISSUE THREAD

**Issue by duchengyao** [leolovenet/qqwry2mmdb#3]
作者你好，我想在转换中尽可能保留所有的信息，给我的geoip服务器用

我在[这里](https://zhuanlan.zhihu.com/p/360624952)看到了dat 文件的定义，但我实在读不懂perl文件，想问一下Dumper.pm已经输出所有的数据了吗？

在这里看到只保存 city.names.en 与 country.names.en，如果Dumper已经把所有数据读出来了，是不是直接在这里改动一下把数据写进去就行了。

https://github.com/leolovenet/qqwry2mmdb/blob/90754c1fab35b9162c7d66473a3a8ed993a3c9de/qqwry2mmdb.pl#L42

能否提示一下如何把所有数据都写进去，万分感激^_^

**Comment by leolovenet** [comment]
> Dumper.pm已经输出所有的数据了吗？

是的，[Dumper.pm](https://github.com/leolovenet/qqwry2mmdb/blob/master/lib/IP/QQWry/Dumper.pm) 是基于 [IP::QQWry](https://metacpan.org/pod/IP::QQWry) 的 [query](https://metacpan.org/pod/IP::QQWry#query) 方法的扩展，它的文档也写到

> In list context, it returns a list containing the base part and the extension part of infomation, respectively. The base part is usually called the country part though it doesn't refer to country all the time. The extension part is usually called the area part.

它只返回 base 与 extension  两部分数据， 就像我的扩展 `iterate` 中[用到的](https://github.com/leolovenet/qqwry2mmdb/blob/90754c1fab35b9162c7d66473a3a8ed993a3c9de/lib/IP/QQWry/Dumper.pm#L42)一样




> 是不是直接在这里改动一下把数据写进去就行了

我没有很理解你最终想要什么，所以，不知道如何回答。

但是，我可以讲一下 [wireshark 读取 mmdb 数据](https://github.com/wireshark/wireshark/blob/2faaf6c33b2c527f68e28ad8e126088065b6464e/epan/maxmind_db.c#L118)的逻辑，但愿会对你有所帮助。

wireshak 的安装包里有一个 `mmdbresolve` 的可执行文件，负责解析 mmdb 文件，并返回查询结果的字符串，最终通过管道传递回 wireshak 处理，在 macOS 下，可以通过下面的命令，手工模拟这一行为。我的 mmdb 保存路径为 `~/PerlProjects/qqwry2mmdb/qqwry.mmdb`：

```
echo 1.1.1.1  |  /Applications/Wireshark.app/Contents/MacOS/mmdbresolve -f ~/PerlProjects/qqwry2mmdb/qqwry.mmdb
```

所以，其实 wireshark 还会读取其他的一些字段比如 `country.iso_code`，你可以根据自己的需求添加。

**Comment by duchengyao** [comment]
原来是这样
感谢回复，我先学一下perl的语法 ^_^
